service: serverless-rds-service

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-north-1

functions:
  serverWithDatabase:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{any+}
